#!/bin/bash

#Script que diciona musica do youtube a playlist do mpd

search=$@
info=$(youtube-dl --get-filename -o '%(id)s---%(title)s' "ytsearch:'$search'")
id=$(echo $info | awk -F'---' '{print $1}')
title=$(echo $info | awk -F'---' '{print $2}')
sh ~/.scripts/music_player.sh --id="$id" --title="$title"

